 - name: Deploy Maven Artifact
   hosts: localhost
   become: no
   tasks:
     - name: Copy artifact
       ansible.builtin.copy:
         src: /home/ai063f09-lr/CalculatorApp/target/CalculatorApp-1.0-SNAPSHOT.jar
         dest: /opt/deployment/CalculatorApp-1.0-SNAPSHOT.jar
