---
- name: Deploy Maven Artifact
  hosts: localhost
  become: true  # Run tasks as root or a privileged user
  tasks:
    - name: Copy the artifact
      ansible.builtin.copy:
        src: /home/ai063f09-lr/myRepo/CalculatorApp-1.0-SNAPSHOT.jar
        dest: /opt/deployment/CalculatorApp-1.0-SNAPSHOT.jar
